query siteById ($id: ID!) {
  site (
    where: {
    id: $id
    }) {
    artist {
      name
      description
      website
      facebook
      twitter
      snapchat
      instagram
      streams(orderBy: time_DESC) {
        title
        venue
        venueUrl
        embed
        time
        description
      }
    }
  }
}